typedef enum {
    TOKEN_LBRACE = 1,
    TOKEN_RBRACE,
    TOKEN_LBRACKET,
    TOKEN_RBRACKET,
    TOKEN_COMMA,
    TOKEN_COLON,
    TOKEN_STRING,
    TOKEN_NUMBER,
    TOKEN_TRUE,
    TOKEN_FALSE,
    TOKEN_NULL,
    TOKEN_WHITESPACE,
    TOKEN_ERROR,
    TOKEN_EOF
} token_t;
